# Generated by Django 5.1.3 on 2024-12-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsession',
            name='created_at',
        ),
    ]
