# Generated by Django 5.1.3 on 2024-12-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
