# Generated by Django 5.1.3 on 2024-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
